/**
 * GitHub PR comment formatter — generates structured comments from graph analysis.
 *
 * Pure function: takes PR metadata + graph data, returns a markdown comment body.
 * No HTTP calls, no GitHub API — just formatting. The caller (webhook, CLI, etc.)
 * posts the comment via their own transport.
 */

export interface PRFile {
  filename: string;
  status: 'added' | 'modified' | 'deleted' | 'renamed';
  additions: number;
  deletions: number;
}

export interface PRMetadata {
  number: number;
  title: string;
  author: string;
  baseBranch: string;
  headBranch: string;
}

export interface GraphNodeSummary {
  path: string;
  rating: number;
  directDependents: number;
  fragileDependents: number;
  errors: number;
  warnings: number;
}

export interface CommentSection {
  icon: string;
  title: string;
  body: string;
}

export type CommentVerdict = 'approve' | 'request-changes' | 'neutral';

export interface FormattedComment {
  verdict: CommentVerdict;
  body: string;
}

/**
 * Generate a PR comment from graph analysis data.
 *
 * @param pr        PR metadata (number, title, author, branches)
 * @param files     Changed files with graph context
 * @param repoName  Short repo name (e.g. "gate-keeper")
 * @param allFilesCount Total files in the graph (for context)
 */
export function formatPRComment(
  pr: PRMetadata,
  files: GraphNodeSummary[],
  repoName: string,
  allFilesCount: number,
): FormattedComment {
  const sections: CommentSection[] = [];

  // Risk assessment header
  const redFiles = files.filter(f => f.rating < 5 || f.fragileDependents >= 3);
  const yellowFiles = files.filter(f => (f.rating >= 5 && f.rating < 7) || f.fragileDependents >= 1);
  const greenFiles = files.filter(f => f.rating >= 7 && f.fragileDependents === 0);

  const verdict: CommentVerdict = redFiles.length > 0
    ? 'request-changes'
    : yellowFiles.length > 0
      ? 'neutral'
      : 'approve';

  // Risk table
  const riskLines: string[] = [
    '| File | Rating | Dependents | Fragile | Risk |',
    '|------|--------|------------|---------|------|',
  ];
  for (const f of files) {
    const isRed = f.rating < 5 || f.fragileDependents >= 3;
    const isYellow = !isRed && ((f.rating >= 5 && f.rating < 7) || f.fragileDependents >= 1);
    const risk = isRed ? '🔴 **HIGH**' : isYellow ? '🟡 MEDIUM' : '🟢 LOW';
    riskLines.push(
      `| ${f.path} | ${f.rating}/10 | ${f.directDependents} | ${f.fragileDependents} | ${risk} |`,
    );
  }

  sections.push({
    icon: '📊',
    title: 'Impact Analysis',
    body: [
      `**${redFiles.length} high-risk** · ${yellowFiles.length} medium · ${greenFiles.length} low`,
      '',
      ...riskLines,
    ].join('\n'),
  });

  // Warnings for high-risk files
  if (redFiles.length > 0) {
    sections.push({
      icon: '🚨',
      title: 'High Risk Changes',
      body: redFiles.map(f => {
        const reasons: string[] = [];
        if (f.rating < 5) reasons.push(`low quality (${f.rating}/10)`);
        if (f.fragileDependents >= 3) reasons.push(`${f.fragileDependents} fragile dependents`);
        if (f.directDependents >= 10) reasons.push(`${f.directDependents} dependents (god node)`);
        return `- **${f.path}**: ${reasons.join(', ')}`;
      }).join('\n'),
    });
  }

  // Verification suggestions
  if (files.some(f => f.directDependents > 0)) {
    const testHints = files
      .filter(f => f.directDependents > 0)
      .slice(0, 5)
      .map(f => `- Run \`get_impact_set("${f.path}", depth=1)\` to verify downstream files still pass`);
    sections.push({
      icon: '✅',
      title: 'Suggested Verification',
      body: testHints.join('\n'),
    });
  }

  // Build the full comment body
  const body = [
    `## Gate Keeper — PR #${pr.number}: ${pr.title}`,
    `_Author: ${pr.author} · Branch: \`${pr.headBranch}\` → \`${pr.baseBranch}\`_`,
    `**Codebase context:** ${allFilesCount} analyzed files in \`${repoName}\``,
    '',
    ...sections.flatMap(s => [`### ${s.icon} ${s.title}`, '', s.body, '']),
    '---',
    `_Generated by Gate Keeper using the dependency graph._`,
    '',
  ].join('\n');

  return { verdict, body };
}

/**
 * Generate a dependency diff between two points in time.
 * Useful for "this PR adds K new dependencies" analysis.
 */
export function formatDependencyDiff(
  addedDeps: Array<{ source: string; target: string; type: string }>,
  removedDeps: Array<{ source: string; target: string; type: string }>,
): string {
  const lines: string[] = ['### 🔗 Dependency Diff', ''];

  if (addedDeps.length > 0) {
    lines.push(`**Added (${addedDeps.length}):**`);
    for (const d of addedDeps.slice(0, 10)) {
      lines.push(`- \`${d.source}\` → \`${d.target}\` [${d.type}]`);
    }
    if (addedDeps.length > 10) lines.push(`_... and ${addedDeps.length - 10} more_`);
    lines.push('');
  }

  if (removedDeps.length > 0) {
    lines.push(`**Removed (${removedDeps.length}):**`);
    for (const d of removedDeps.slice(0, 10)) {
      lines.push(`- \`${d.source}\` → \`${d.target}\` [${d.type}]`);
    }
    if (removedDeps.length > 10) lines.push(`_... and ${removedDeps.length - 10} more_`);
    lines.push('');
  }

  if (addedDeps.length === 0 && removedDeps.length === 0) {
    lines.push('No dependency changes detected.');
  }

  return lines.join('\n');
}

/**
 * Generate a suggested reviewers list based on module ownership.
 * Files in the PR are grouped by module; the most-committing author
 * of each module is suggested.
 */
export function formatSuggestedReviewers(
  prFiles: PRFile[],
  owners: Map<string, string[]>,
  repoRoot: string,
): string {
  const lines: string[] = ['### 👥 Suggested Reviewers', ''];
  const seen = new Set<string>();

  for (const file of prFiles) {
    const rel = file.filename;
    const reviewers = owners.get(rel) ?? owners.get(pathDir(rel, repoRoot)) ?? [];
    for (const r of reviewers) {
      if (!seen.has(r)) {
        seen.add(r);
        lines.push(`- **@${r}** — owns/modified ${rel}`);
      }
    }
  }

  if (seen.size === 0) {
    lines.push('No ownership data available for changed files.');
  }

  return lines.join('\n');
}

function pathDir(filePath: string, _repoRoot: string): string {
  // Returns the top-level directory of a relative path, or '(root)'
  const parts = filePath.split('/').filter(Boolean);
  if (parts.length <= 1) return '(root)';
  if (['src', 'lib', 'app'].includes(parts[0]!) && parts.length > 2) return parts[1]!;
  return parts[0]!;
}
