/**
 * Narrative knowledge-graph report generator (graphify-style GRAPH_REPORT.md).
 *
 * Produces a Markdown document with:
 *  - God nodes (highest centrality)
 *  - Surprising cross-module connections
 *  - Auto-generated suggested questions
 *  - Architecture overview (module breakdown + cycles)
 *
 * Pure function — no I/O, no daemon dependency.
 */

import * as path from 'path';
import { computeCentrality } from './graph-algorithms';
import { findSurprisingConnections, getModule } from './surprising-connections';
import { suggestQuestions } from './question-suggester';

interface GNode { id: string; label: string; rating: number; metrics?: { linesOfCode?: number } }
interface GEdge { source: string; target: string }
interface CycleInfo { nodes: string[] }

export interface GraphReportOptions {
  topGodNodes?: number;
  topSurprising?: number;
  maxQuestions?: number;
}

export function generateGraphReport(
  nodes: ReadonlyArray<GNode>,
  edges: ReadonlyArray<GEdge>,
  cycles: ReadonlyArray<CycleInfo>,
  repoRoot: string,
  overallRating: number | null,
  opts: GraphReportOptions = {},
): string {
  const { topGodNodes = 5, topSurprising = 5, maxQuestions = 5 } = opts;
  const repoName = path.basename(repoRoot);

  const centrality = computeCentrality(nodes as GNode[], edges as GEdge[]);
  const godNodes = centrality.slice(0, topGodNodes);
  const surprising = findSurprisingConnections(nodes, edges, repoRoot, topSurprising);
  const questions = suggestQuestions(nodes as GNode[], edges as GEdge[], repoRoot, maxQuestions);

  const lines: string[] = [];

  lines.push(`# Knowledge Graph: ${repoName}`);
  lines.push('');
  lines.push(
    `**Files:** ${nodes.length} | **Relationships:** ${edges.length} | ` +
    `**Overall Quality:** ${overallRating?.toFixed(1) ?? 'N/A'}/10 | ` +
    `**Cycles:** ${cycles.length}`,
  );
  lines.push('');

  // God Nodes
  if (godNodes.length > 0) {
    lines.push('## God Nodes (Highest Blast Radius)');
    lines.push('_These files are most dangerous to change — many others depend on them._');
    lines.push('');
    for (let i = 0; i < godNodes.length; i++) {
      const n = godNodes[i]!;
      const rel = path.relative(repoRoot, n.path);
      const riskIcon = n.rating < 6 ? '🔴' : n.rating < 8 ? '🟡' : '🟢';
      lines.push(
        `${i + 1}. ${riskIcon} **${rel}** — ${n.totalDegree} connections ` +
        `(in: ${n.inDegree}, out: ${n.outDegree}), rating ${n.rating}/10`,
      );
    }
    lines.push('');
  }

  // Surprising Connections
  if (surprising.length > 0) {
    lines.push('## Surprising Connections');
    lines.push('_Cross-module dependencies that may indicate unexpected coupling._');
    lines.push('');
    for (const s of surprising) {
      const src = path.relative(repoRoot, s.source);
      const tgt = path.relative(repoRoot, s.target);
      lines.push(`- **${src}** → **${tgt}**`);
      lines.push(`  _${s.explanation}_`);
    }
    lines.push('');
  }

  // Suggested Questions
  if (questions.length > 0) {
    lines.push('## Suggested Questions');
    lines.push('_Questions the graph is positioned to answer with a single MCP call._');
    lines.push('');
    questions.forEach((q, i) => {
      lines.push(`${i + 1}. ${q.question}`);
      lines.push(`   → \`${q.tool}\` with \`${JSON.stringify(q.params)}\``);
    });
    lines.push('');
  }

  // Architecture Overview
  lines.push('## Architecture Overview');
  const moduleCounts = new Map<string, number>();
  const moduleRatings = new Map<string, number[]>();
  for (const n of nodes) {
    const mod = getModule(n.id, repoRoot);
    moduleCounts.set(mod, (moduleCounts.get(mod) ?? 0) + 1);
    (moduleRatings.get(mod) ?? moduleRatings.set(mod, []).get(mod)!).push(n.rating);
  }

  const moduleList = [...moduleCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);

  lines.push('');
  lines.push('| Module | Files | Avg Rating |');
  lines.push('|--------|-------|------------|');
  for (const [mod, count] of moduleList) {
    const ratings = moduleRatings.get(mod) ?? [];
    const avg = ratings.length > 0
      ? (ratings.reduce((s, r) => s + r, 0) / ratings.length).toFixed(1)
      : 'N/A';
    lines.push(`| ${mod} | ${count} | ${avg}/10 |`);
  }

  if (cycles.length > 0) {
    lines.push('');
    lines.push(
      `⚠️ **${cycles.length} circular dependency cycle${cycles.length !== 1 ? 's' : ''} detected** ` +
      `— each costs −1.0 rating. Run \`get_dependency_graph\` to see the full list.`,
    );
  }

  lines.push('');
  lines.push('---');
  lines.push(`_Generated by Gate Keeper at ${new Date().toISOString()}_`);

  return lines.join('\n');
}
