/**
 * Tests for graph-intelligence MCP handlers.
 * The pure resolveQueryPattern is already tested in graph-query-nl.test.ts.
 * Here we cover the async daemon-calling handlers.
 */

import {
  handleGetGraphReport,
  handleQueryGraph,
  handleExplainNode,
  handleExportGraph,
  handleMergeGraphs,
  handleGetGraphViz,
} from './graph-intelligence';
import { fetchDaemonApi } from '../helpers';

jest.mock('../helpers', () => ({
  fetchDaemonApi: jest.fn(),
  findGitRoot: jest.fn().mockReturnValue('/repo'),
}));

jest.mock('fs', () => ({
  mkdirSync: jest.fn(),
  writeFileSync: jest.fn(),
}));

jest.mock('os', () => ({ homedir: () => '/home/test' }));

const mockFetch = fetchDaemonApi as jest.MockedFunction<typeof fetchDaemonApi>;

// ── Fixtures ───────────────────────────────────────────────

const mkNode = (id: string, rating: number) => ({
  id, label: id.split('/').pop()!, type: 'typescript', rating, size: 1, violations: [],
  metrics: { linesOfCode: 80, cyclomaticComplexity: 4, numberOfMethods: 3, numberOfClasses: 0, importCount: 2 },
});

const GRAPH = {
  nodes: [
    mkNode('/repo/src/auth/service.ts', 8),
    mkNode('/repo/src/db/pool.ts', 4),
    mkNode('/repo/src/api/router.ts', 7),
  ],
  edges: [
    { source: '/repo/src/api/router.ts', target: '/repo/src/auth/service.ts', type: 'import', strength: 1 },
    { source: '/repo/src/auth/service.ts', target: '/repo/src/db/pool.ts', type: 'import', strength: 1 },
  ],
};

const DAEMON_ERR = 'daemon is not running';

// ── handleGetGraphReport ───────────────────────────────────

describe('handleGetGraphReport', () => {
  it('returns daemon error when graph fetch fails', async () => {
    mockFetch.mockResolvedValue(null);
    const r = await handleGetGraphReport({});
    expect(r.content[0]!.text).toContain(DAEMON_ERR);
  });

  it('returns report with node/edge counts', async () => {
    mockFetch
      .mockResolvedValueOnce(GRAPH)     // graph
      .mockResolvedValueOnce([])         // cycles
      .mockResolvedValueOnce({ overallRating: 7.2 }); // status
    const r = await handleGetGraphReport({ repo: '/repo' });
    const text = r.content[0]!.text;
    expect(text).toBeDefined();
    // The report is generated by generateGraphReport — just check it is non-empty
    expect(text.length).toBeGreaterThan(0);
  });

  it('handles missing status gracefully', async () => {
    mockFetch
      .mockResolvedValueOnce(GRAPH)
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce(null); // no status
    const r = await handleGetGraphReport({});
    expect(r.content[0]!.text).toBeDefined();
  });
});

// ── handleQueryGraph ───────────────────────────────────────

describe('handleQueryGraph', () => {
  it('returns error when query is empty', async () => {
    const r = await handleQueryGraph({ query: '' });
    expect(r.content[0]!.text).toContain('query is required');
  });

  it('returns daemon error when fetch fails', async () => {
    mockFetch.mockResolvedValue(null);
    const r = await handleQueryGraph({ query: 'show god nodes' });
    expect(r.content[0]!.text).toContain(DAEMON_ERR);
  });

  it('answers a matched pattern query', async () => {
    mockFetch.mockResolvedValue(GRAPH);
    const r = await handleQueryGraph({ query: 'show me god nodes' });
    const text = r.content[0]!.text;
    expect(text).toContain('Query:');
    expect(text).toContain('connections');
  });

  it('returns suggested questions for unrecognised query', async () => {
    mockFetch.mockResolvedValue(GRAPH);
    const r = await handleQueryGraph({ query: 'zzz unrecognised zzz' });
    const text = r.content[0]!.text;
    expect(text).toContain('Query not recognized');
  });
});

// ── handleExplainNode ──────────────────────────────────────

describe('handleExplainNode', () => {
  it('returns error when file_path is missing', async () => {
    const r = await handleExplainNode({});
    expect(r.content[0]!.text).toContain('file_path is required');
  });

  it('returns daemon error when graph fetch fails', async () => {
    mockFetch.mockResolvedValue(null);
    const r = await handleExplainNode({ file_path: '/repo/src/auth/service.ts' });
    expect(r.content[0]!.text).toContain(DAEMON_ERR);
  });

  it('prompts to analyze when node not in graph', async () => {
    mockFetch
      .mockResolvedValueOnce({ nodes: [], edges: [] }) // graph empty
      .mockResolvedValueOnce(null);                     // detail empty
    const r = await handleExplainNode({ file_path: '/repo/src/unknown.ts' });
    expect(r.content[0]!.text).toContain('analyze_file');
  });

  it('returns node explanation with rating and centrality', async () => {
    mockFetch
      .mockResolvedValueOnce(GRAPH)     // graph
      .mockResolvedValueOnce({ analysis: { rating: 8, metrics: {}, violations: [] } }); // detail
    const r = await handleExplainNode({ file_path: '/repo/src/auth/service.ts' });
    const text = r.content[0]!.text;
    expect(text).toContain('Node Explanation');
    expect(text).toContain('service.ts');
  });
});

// ── handleExportGraph ──────────────────────────────────────

describe('handleExportGraph', () => {
  it('returns error for invalid format', async () => {
    const r = await handleExportGraph({ format: 'csv' });
    expect(r.content[0]!.text).toContain('format must be');
  });

  it('returns daemon error when fetch fails', async () => {
    mockFetch.mockResolvedValue(null);
    const r = await handleExportGraph({ format: 'json' });
    expect(r.content[0]!.text).toContain(DAEMON_ERR);
  });

  it('exports JSON format successfully', async () => {
    mockFetch
      .mockResolvedValueOnce(GRAPH)
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce(null);
    const r = await handleExportGraph({ format: 'json', repo: '/repo' });
    expect(r.content[0]!.text).toContain('Graph Export: JSON');
  });

  it('exports graphml format', async () => {
    mockFetch
      .mockResolvedValueOnce(GRAPH)
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce(null);
    const r = await handleExportGraph({ format: 'graphml', repo: '/repo' });
    expect(r.content[0]!.text).toContain('GRAPHML');
  });
});

// ── handleMergeGraphs ──────────────────────────────────────

describe('handleMergeGraphs', () => {
  it('returns error when repo_a or repo_b is missing', async () => {
    const r = await handleMergeGraphs({ repo_a: '/a' });
    expect(r.content[0]!.text).toContain('required');
  });

  it('returns error when repo_a fetch fails', async () => {
    mockFetch.mockResolvedValueOnce(null).mockResolvedValueOnce(GRAPH);
    const r = await handleMergeGraphs({ repo_a: '/a', repo_b: '/b' });
    expect(r.content[0]!.text).toContain('repo_a');
  });

  it('returns error when repo_b fetch fails', async () => {
    mockFetch.mockResolvedValueOnce(GRAPH).mockResolvedValueOnce(null);
    const r = await handleMergeGraphs({ repo_a: '/a', repo_b: '/b' });
    expect(r.content[0]!.text).toContain('repo_b');
  });

  it('merges two graphs and returns merged count', async () => {
    mockFetch.mockResolvedValueOnce(GRAPH).mockResolvedValueOnce(GRAPH);
    const r = await handleMergeGraphs({ repo_a: '/a', repo_b: '/b' });
    expect(r.content[0]!.text).toContain('Merged Graph');
  });
});

// ── handleGetGraphViz ──────────────────────────────────────

describe('handleGetGraphViz', () => {
  it('returns daemon error when fetch fails', async () => {
    mockFetch.mockResolvedValue(null);
    const r = await handleGetGraphViz({});
    expect(r.content[0]!.text).toContain(DAEMON_ERR);
  });

  it('writes HTML file and returns path in output', async () => {
    mockFetch.mockResolvedValue(GRAPH);
    const r = await handleGetGraphViz({ repo: '/repo' });
    const text = r.content[0]!.text;
    expect(text).toContain('Written to');
    expect(text).toContain('.html');
  });
});
